<a href="https://colab.research.google.com/github/PRAN20/EEG-Emotions/blob/main/All_Classification_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Calculating Accuracy by Using Different Classification**

# **Importing Header Files**

In [1]:
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
import os

# **Importing DataSet**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#os.makedirs('dataset')

In [20]:
!unzip "/content/drive/MyDrive/Split-Output-EEG.zip" -d "dataset"

Archive:  /content/drive/MyDrive/Split-Output-EEG.zip
 extracting: dataset/content/Split-Output-EEG/X_test.csv  
 extracting: dataset/content/Split-Output-EEG/Y_test.csv  
 extracting: dataset/content/Split-Output-EEG/Y_train.csv  
 extracting: dataset/content/Split-Output-EEG/X_train.csv  
 extracting: dataset/content/Split-Output-EEG/Labels.png  


In [23]:
import pandas as pd
train_images=pd.read_csv("/content/dataset/content/Output/X_train.csv",header=None)
x_train=train_images.iloc[:,:].values
x_train.shape

(1917, 2)

In [24]:
train_labels=pd.read_csv("/content/dataset/content/Output/Y_train.csv",header=None)
y_train=train_labels.iloc[:,:].values
y_train= y_train.flatten()
y_train.shape

(1917,)

In [25]:
import pandas as pd
test_images=pd.read_csv("/content/dataset/content/Output/X_test.csv",header=None)
x_test=test_images.iloc[:,:].values
x_test.shape

(213, 2)

In [26]:
test_labels=pd.read_csv("/content/dataset/content/Output/Y_test.csv",header=None)
y_test=test_labels.iloc[:,:].values
y_test= y_test.flatten()
y_test.shape

(213,)

# **Determing The Shape of all The Data**

In [7]:
x_train.shape

(1917, 2)

In [8]:
y_train.shape

(1917,)

In [9]:
x_test.shape

(1917, 2)

In [10]:
y_test.shape

(213,)

# **Training The MLP Model**

In [27]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(max_iter = 500, activation = 'relu')
classifier.fit(x_train, y_train)

MLPClassifier(max_iter=500)

**Testing the Model**

In [28]:
y_pred = classifier.predict(x_test)

In [29]:
print(y_pred)
y_pred.shape

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


(213,)

**Confusion Matrix**

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 0, 75,  0],
       [ 0, 70,  0],
       [ 0, 68,  0]])

**Calculating the Accuracy of the Model**

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        75
         1.0       0.33      1.00      0.49        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.33       213
   macro avg       0.11      0.33      0.16       213
weighted avg       0.11      0.33      0.16       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
from sklearn.metrics import accuracy_score
mlp = accuracy_score(y_test, y_pred)
mlp

0.3286384976525822

# **Naive-Bays Model**

In [33]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [34]:
y_pred = clf.predict(x_test)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
naive = accuracy_score(y_test, y_pred)
naive

[[ 0 75  0]
 [ 0 70  0]
 [ 0 68  0]]


0.3286384976525822

In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        75
         1.0       0.33      1.00      0.49        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.33       213
   macro avg       0.11      0.33      0.16       213
weighted avg       0.11      0.33      0.16       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Random Forest Classification**

In [37]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators = 70, oob_score = True, n_jobs = -1,max_features = None, min_samples_leaf = 30)
clf1.fit(x_train, y_train)

RandomForestClassifier(max_features=None, min_samples_leaf=30, n_estimators=70,
                       n_jobs=-1, oob_score=True)

In [38]:
y_pred = clf1.predict(x_test)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
rand = accuracy_score(y_test, y_pred)
rand

[[75  0  0]
 [70  0  0]
 [68  0  0]]


0.352112676056338

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.35      1.00      0.52        75
         1.0       0.00      0.00      0.00        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.35       213
   macro avg       0.12      0.33      0.17       213
weighted avg       0.12      0.35      0.18       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **K-NN**

In [41]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
kn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [42]:
y_pred = kn.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
knn = accuracy_score(y_test, y_pred)
knn

[[75  0  0]
 [70  0  0]
 [68  0  0]]


0.352112676056338

In [44]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.35      1.00      0.52        75
         1.0       0.00      0.00      0.00        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.35       213
   macro avg       0.12      0.33      0.17       213
weighted avg       0.12      0.35      0.18       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Decision Tree**

In [45]:
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier(max_depth = 10, random_state = 101, max_features = None, min_samples_leaf = 15)
clf2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=15, random_state=101)

In [46]:
y_pred = clf2.predict(x_test)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
desc = accuracy_score(y_test, y_pred)
desc

[[75  0  0]
 [70  0  0]
 [68  0  0]]


0.352112676056338

In [48]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.35      1.00      0.52        75
         1.0       0.00      0.00      0.00        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.35       213
   macro avg       0.12      0.33      0.17       213
weighted avg       0.12      0.35      0.18       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Kernel SVM**

In [49]:
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'linear', C =  1,  random_state = 101)
classifier1.fit(x_train, y_train)

SVC(C=1, kernel='linear', random_state=101)

In [50]:
y_pred = classifier1.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svm = accuracy_score(y_test, y_pred)
svm

[[ 0 75  0]
 [ 0 70  0]
 [ 0 68  0]]


0.3286384976525822

In [52]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        75
         1.0       0.33      1.00      0.49        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.33       213
   macro avg       0.11      0.33      0.16       213
weighted avg       0.11      0.33      0.16       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Linear SVC**

In [53]:
from sklearn.svm import LinearSVC
class3 = LinearSVC(random_state=0, tol=1e-5)
class3.fit(x_train, y_train)

LinearSVC(random_state=0, tol=1e-05)

In [54]:
y_pred = class3.predict(x_test)

In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svc = accuracy_score(y_test, y_pred)
svc

[[ 0 75  0]
 [ 0 70  0]
 [ 0 68  0]]


0.3286384976525822

In [56]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        75
         1.0       0.33      1.00      0.49        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.33       213
   macro avg       0.11      0.33      0.16       213
weighted avg       0.11      0.33      0.16       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Logistic Regression**

In [57]:
from sklearn.linear_model import LogisticRegression
classifier4 = LogisticRegression(random_state = 0)
classifier4.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [58]:
y_pred = classifier4.predict(x_test)

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
logis = accuracy_score(y_test, y_pred)
logis

[[ 0 75  0]
 [ 0 70  0]
 [ 0 68  0]]


0.3286384976525822

In [60]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        75
         1.0       0.33      1.00      0.49        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.33       213
   macro avg       0.11      0.33      0.16       213
weighted avg       0.11      0.33      0.16       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Stochastic Gradient Descent**

In [61]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss = 'modified_huber', shuffle = True, random_state = 101)
sgd.fit(x_train, y_train)

SGDClassifier(loss='modified_huber', random_state=101)

In [62]:
y_pred = sgd.predict(x_test)

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
stoc = accuracy_score(y_test, y_pred)
stoc

[[ 0  0 75]
 [ 0  0 70]
 [ 0  0 68]]


0.3192488262910798

In [65]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        75
         1.0       0.00      0.00      0.00        70
         2.0       0.32      1.00      0.48        68

    accuracy                           0.32       213
   macro avg       0.11      0.33      0.16       213
weighted avg       0.10      0.32      0.15       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Final Results**

In [66]:
print('Accuracy of MLP Model is {}'.format(mlp))
print('Accuracy of Naive-Bays Model is {}'.format(naive))
print('Accuracy of Random Forest Model is {}'.format(rand))
print('Accuracy of K-NN Model is {}'.format(knn))
print('Accuracy of Decision Tree Model is {}'.format(desc))
print('Accuracy of Kernel Svm Model is {}'.format(svm))
print('Accuracy of Linear SVC Model is {}'.format(svc))
print('Accuracy of Logistic Regression Model is {}'.format(logis))
print('Accuracy of Stochastic Gradient Descent Model is {}'.format(stoc))

Accuracy of MLP Model is 0.3286384976525822
Accuracy of Naive-Bays Model is 0.3286384976525822
Accuracy of Random Forest Model is 0.352112676056338
Accuracy of K-NN Model is 0.352112676056338
Accuracy of Decision Tree Model is 0.352112676056338
Accuracy of Kernel Svm Model is 0.3286384976525822
Accuracy of Linear SVC Model is 0.3286384976525822
Accuracy of Logistic Regression Model is 0.3286384976525822
Accuracy of Stochastic Gradient Descent Model is 0.3192488262910798
