<a href="https://colab.research.google.com/github/PRAN20/EEG-Emotions/blob/main/Final-Result_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Calculating Accuracy by Using Different Classification**

# **Importing Header Files**

In [1]:
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
import os

# **Importing DataSet**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#os.makedirs('dataset')

In [20]:
!unzip "/content/drive/MyDrive/Split-Output-EEG.zip" -d "dataset"

Archive:  /content/drive/MyDrive/Split-Output-EEG.zip
 extracting: dataset/content/Split-Output-EEG/X_test.csv  
 extracting: dataset/content/Split-Output-EEG/Y_test.csv  
 extracting: dataset/content/Split-Output-EEG/Y_train.csv  
 extracting: dataset/content/Split-Output-EEG/X_train.csv  
 extracting: dataset/content/Split-Output-EEG/Labels.png  


In [2]:
import pandas as pd
train_images=pd.read_csv("/content/dataset/content/Split-Output-EEG/X_train.csv",header=None)
x_train=train_images.iloc[:,:].values
x_train.shape

(1918, 2548)

In [3]:
train_labels=pd.read_csv("/content/dataset/content/Split-Output-EEG/Y_train.csv",header=None)
y_train=train_labels.iloc[:,:].values
y_train= y_train.flatten()
y_train.shape

(1918,)

In [4]:
import pandas as pd
test_images=pd.read_csv("/content/dataset/content/Split-Output-EEG/X_test.csv",header=None)
x_test=test_images.iloc[:,:].values
x_test.shape

(214, 2548)

In [5]:
test_labels=pd.read_csv("/content/dataset/content/Split-Output-EEG/Y_test.csv",header=None)
y_test=test_labels.iloc[:,:].values
y_test= y_test.flatten()
y_test.shape

(214,)

# **Determing The Shape of all The Data**

In [7]:
x_train.shape

(1917, 2)

In [8]:
y_train.shape

(1917,)

In [9]:
x_test.shape

(1917, 2)

In [10]:
y_test.shape

(213,)

# **Training The MLP Model**

In [6]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(max_iter = 500, activation = 'relu')
classifier.fit(x_train, y_train)

MLPClassifier(max_iter=500)

**Testing the Model**

In [7]:
y_pred = classifier.predict(x_test)

In [8]:
print(y_pred)
y_pred.shape

[0. 0. 0. 0. 2. 2. 2. 2. 0. 2. 0. 0. 0. 2. 0. 0. 0. 0. 2. 2. 2. 2. 0. 2.
 0. 0. 2. 0. 0. 0. 0. 0. 0. 2. 0. 2. 2. 0. 0. 2. 0. 2. 0. 0. 2. 2. 2. 0.
 2. 2. 1. 0. 2. 0. 2. 2. 2. 2. 0. 2. 2. 0. 2. 2. 0. 2. 0. 2. 2. 1. 2. 2.
 0. 2. 0. 2. 0. 0. 0. 2. 2. 2. 0. 0. 2. 0. 2. 2. 2. 2. 2. 1. 0. 0. 0. 2.
 0. 0. 0. 2. 0. 0. 2. 0. 2. 2. 0. 2. 2. 0. 1. 2. 2. 0. 2. 0. 0. 0. 2. 0.
 0. 2. 2. 2. 0. 2. 0. 2. 0. 2. 0. 0. 0. 2. 2. 2. 0. 2. 1. 0. 0. 2. 0. 0.
 0. 0. 2. 2. 2. 0. 2. 0. 0. 0. 0. 0. 0. 2. 0. 1. 2. 2. 0. 2. 2. 2. 2. 0.
 2. 0. 0. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1. 0. 2. 2. 2. 2. 2. 2. 2. 0. 2. 0.
 0. 0. 2. 2. 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 2. 2. 0.]


(214,)

**Confusion Matrix**

In [9]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[74,  1,  1],
       [ 5,  1, 64],
       [24,  5, 39]])

**Calculating the Accuracy of the Model**

In [10]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.72      0.97      0.83        76
         1.0       0.14      0.01      0.03        70
         2.0       0.38      0.57      0.45        68

    accuracy                           0.53       214
   macro avg       0.41      0.52      0.44       214
weighted avg       0.42      0.53      0.45       214



In [11]:
from sklearn.metrics import accuracy_score
mlp = accuracy_score(y_test, y_pred)
mlp

0.5327102803738317

# **Naive-Bays Model**

In [12]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [13]:
y_pred = clf.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
naive = accuracy_score(y_test, y_pred)
naive

[[ 0 21 55]
 [ 0 69  1]
 [ 0 50 18]]


0.40654205607476634

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        76
         1.0       0.49      0.99      0.66        70
         2.0       0.24      0.26      0.25        68

    accuracy                           0.41       214
   macro avg       0.25      0.42      0.30       214
weighted avg       0.24      0.41      0.30       214



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Random Forest Classification**

In [37]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators = 70, oob_score = True, n_jobs = -1,max_features = None, min_samples_leaf = 30)
clf1.fit(x_train, y_train)

RandomForestClassifier(max_features=None, min_samples_leaf=30, n_estimators=70,
                       n_jobs=-1, oob_score=True)

In [38]:
y_pred = clf1.predict(x_test)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
rand = accuracy_score(y_test, y_pred)
rand

[[73  0  3]
 [ 0 69  1]
 [ 6  0 62]]


0.9532710280373832

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.92      0.96      0.94        76
         1.0       1.00      0.99      0.99        70
         2.0       0.94      0.91      0.93        68

    accuracy                           0.95       214
   macro avg       0.95      0.95      0.95       214
weighted avg       0.95      0.95      0.95       214



# **K-NN**

In [16]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
kn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [17]:
y_pred = kn.predict(x_test)

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
knn = accuracy_score(y_test, y_pred)
knn

[[73  0  3]
 [ 5 58  7]
 [24 22 22]]


0.7149532710280374

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.72      0.96      0.82        76
         1.0       0.72      0.83      0.77        70
         2.0       0.69      0.32      0.44        68

    accuracy                           0.71       214
   macro avg       0.71      0.70      0.68       214
weighted avg       0.71      0.71      0.68       214



# **Decision Tree**

In [20]:
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier(max_depth = 10, random_state = 101, max_features = None, min_samples_leaf = 15)
clf2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=15, random_state=101)

In [21]:
y_pred = clf2.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
desc = accuracy_score(y_test, y_pred)
desc

[[71  0  5]
 [ 0 70  0]
 [ 4  3 61]]


0.9439252336448598

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.95      0.93      0.94        76
         1.0       0.96      1.00      0.98        70
         2.0       0.92      0.90      0.91        68

    accuracy                           0.94       214
   macro avg       0.94      0.94      0.94       214
weighted avg       0.94      0.94      0.94       214



# **Kernel SVM**

In [ ]:
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'linear', C =  1,  random_state = 101)
classifier1.fit(x_train, y_train)

In [ ]:
y_pred = classifier1.predict(x_test)

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svm = accuracy_score(y_test, y_pred)

[[73  0  3]
 [ 0 69  1]
 [ 6  0 62]]


In [88]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        75
         1.0       0.33      1.00      0.49        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.33       213
   macro avg       0.11      0.33      0.16       213
weighted avg       0.11      0.33      0.16       213



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Linear SVC**

In [24]:
from sklearn.svm import LinearSVC
class3 = LinearSVC(random_state=0, tol=1e-5)
class3.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC(random_state=0, tol=1e-05)

In [25]:
y_pred = class3.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svc = accuracy_score(y_test, y_pred)
svc

[[ 1  2 73]
 [ 1  4 65]
 [ 0  6 62]]


0.3130841121495327

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.50      0.01      0.03        76
         1.0       0.33      0.06      0.10        70
         2.0       0.31      0.91      0.46        68

    accuracy                           0.31       214
   macro avg       0.38      0.33      0.20       214
weighted avg       0.39      0.31      0.19       214



# **Logistic Regression**

In [28]:
from sklearn.linear_model import LogisticRegression
classifier4 = LogisticRegression(random_state = 0)
classifier4.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [29]:
y_pred = classifier4.predict(x_test)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
logis = accuracy_score(y_test, y_pred)
logis

[[76  0  0]
 [70  0  0]
 [68  0  0]]


0.35514018691588783

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.36      1.00      0.52        76
         1.0       0.00      0.00      0.00        70
         2.0       0.00      0.00      0.00        68

    accuracy                           0.36       214
   macro avg       0.12      0.33      0.17       214
weighted avg       0.13      0.36      0.19       214



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Stochastic Gradient Descent**

In [32]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss = 'modified_huber', shuffle = True, random_state = 101)
sgd.fit(x_train, y_train)

SGDClassifier(loss='modified_huber', random_state=101)

In [33]:
y_pred = sgd.predict(x_test)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
stoc = accuracy_score(y_test, y_pred)
stoc

[[76  0  0]
 [16  0 54]
 [51  0 17]]


0.43457943925233644

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.53      1.00      0.69        76
         1.0       0.00      0.00      0.00        70
         2.0       0.24      0.25      0.24        68

    accuracy                           0.43       214
   macro avg       0.26      0.42      0.31       214
weighted avg       0.26      0.43      0.32       214



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Final Results**

In [41]:
print('Accuracy of MLP Model is {}'.format(mlp))
print('Accuracy of Naive-Bays Model is {}'.format(naive))
print('Accuracy of Random Forest Model is {}'.format(rand))
print('Accuracy of K-NN Model is {}'.format(knn))
print('Accuracy of Decision Tree Model is {}'.format(desc))
print('Accuracy of Kernel Svm Model is {}'.format(svm))
print('Accuracy of Linear SVC Model is {}'.format(svc))
print('Accuracy of Logistic Regression Model is {}'.format(logis))
print('Accuracy of Stochastic Gradient Descent Model is {}'.format(stoc))

Accuracy of MLP Model is 0.5327102803738317
Accuracy of Naive-Bays Model is 0.40654205607476634
Accuracy of Random Forest Model is 0.9532710280373832
Accuracy of K-NN Model is 0.7149532710280374
Accuracy of Decision Tree Model is 0.9439252336448598
Accuracy of Kernel Svm Model is 98.98
Accuracy of Linear SVC Model is 0.3130841121495327
Accuracy of Logistic Regression Model is 0.35514018691588783
Accuracy of Stochastic Gradient Descent Model is 0.43457943925233644
